// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressbook.proto

package tutorial

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}

func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{0, 0}
}

type Person struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Sex                  int32                 `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Email                string                `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phones               []*Person_PhoneNumber `protobuf:"bytes,5,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number               string           `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Person_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=tutorial.Person_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()         { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()    {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{0, 0}
}

func (m *Person_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_PhoneNumber.Unmarshal(m, b)
}
func (m *Person_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Person_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_PhoneNumber.Merge(m, src)
}
func (m *Person_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Person_PhoneNumber.Size(m)
}
func (m *Person_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Person_PhoneNumber proto.InternalMessageInfo

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

// Our address book file is just one of these.
type AddressBook struct {
	People               []*Person `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddressBook) Reset()         { *m = AddressBook{} }
func (m *AddressBook) String() string { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()    {}
func (*AddressBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{1}
}

func (m *AddressBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBook.Unmarshal(m, b)
}
func (m *AddressBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBook.Marshal(b, m, deterministic)
}
func (m *AddressBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBook.Merge(m, src)
}
func (m *AddressBook) XXX_Size() int {
	return xxx_messageInfo_AddressBook.Size(m)
}
func (m *AddressBook) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBook.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBook proto.InternalMessageInfo

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

type Profile struct {
	// Types that are valid to be assigned to Avatar:
	//	*Profile_ImageUrl
	//	*Profile_ImageData
	Avatar               isProfile_Avatar `protobuf_oneof:"avatar"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{2}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

type isProfile_Avatar interface {
	isProfile_Avatar()
}

type Profile_ImageUrl struct {
	ImageUrl string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3,oneof"`
}

type Profile_ImageData struct {
	ImageData []byte `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3,oneof"`
}

func (*Profile_ImageUrl) isProfile_Avatar() {}

func (*Profile_ImageData) isProfile_Avatar() {}

func (m *Profile) GetAvatar() isProfile_Avatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *Profile) GetImageUrl() string {
	if x, ok := m.GetAvatar().(*Profile_ImageUrl); ok {
		return x.ImageUrl
	}
	return ""
}

func (m *Profile) GetImageData() []byte {
	if x, ok := m.GetAvatar().(*Profile_ImageData); ok {
		return x.ImageData
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Profile) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Profile_ImageUrl)(nil),
		(*Profile_ImageData)(nil),
	}
}

func init() {
	proto.RegisterEnum("tutorial.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
	proto.RegisterType((*Person)(nil), "tutorial.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "tutorial.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "tutorial.AddressBook")
	proto.RegisterType((*Profile)(nil), "tutorial.Profile")
}

func init() { proto.RegisterFile("addressbook.proto", fileDescriptor_1eb1a68c9dd6d429) }

var fileDescriptor_1eb1a68c9dd6d429 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xd1, 0x4a, 0xc3, 0x40,
	0x10, 0x6c, 0xd2, 0x34, 0xa6, 0x1b, 0x2d, 0x71, 0x11, 0x09, 0x45, 0xb1, 0xe4, 0x29, 0x20, 0x44,
	0xa8, 0x82, 0xcf, 0x06, 0x0b, 0x15, 0xad, 0x2d, 0xa7, 0x45, 0xf0, 0x45, 0x2e, 0xe4, 0xd4, 0xd0,
	0x24, 0x77, 0x5c, 0xae, 0x62, 0x7f, 0xc2, 0x6f, 0x96, 0x5c, 0x52, 0x11, 0xf1, 0x6d, 0x76, 0x66,
	0xf7, 0x66, 0x76, 0x0f, 0xf6, 0x69, 0x9a, 0x4a, 0x56, 0x55, 0x09, 0xe7, 0xab, 0x48, 0x48, 0xae,
	0x38, 0x3a, 0x6a, 0xad, 0xb8, 0xcc, 0x68, 0x1e, 0x7c, 0x99, 0x60, 0x2f, 0x98, 0xac, 0x78, 0x89,
	0x08, 0x56, 0x49, 0x0b, 0xe6, 0x1b, 0x23, 0x23, 0xec, 0x13, 0x8d, 0x71, 0x00, 0x66, 0x96, 0xfa,
	0xe6, 0xc8, 0x08, 0x7b, 0xc4, 0xcc, 0x52, 0xf4, 0xa0, 0x5b, 0xb1, 0x4f, 0xbf, 0xab, 0x89, 0x1a,
	0xe2, 0x01, 0xf4, 0x58, 0x41, 0xb3, 0xdc, 0xb7, 0xf4, 0x58, 0x53, 0xe0, 0x05, 0xd8, 0xe2, 0x9d,
	0x97, 0xac, 0xf2, 0x7b, 0xa3, 0x6e, 0xe8, 0x8e, 0x8f, 0xa2, 0xad, 0x63, 0xd4, 0xb8, 0x45, 0x8b,
	0x5a, 0xbe, 0x5f, 0x17, 0x09, 0x93, 0xa4, 0xed, 0x1d, 0x2e, 0xc1, 0xfd, 0x45, 0xe3, 0x21, 0xd8,
	0xa5, 0x46, 0x6d, 0xa4, 0xb6, 0xc2, 0x08, 0x2c, 0xb5, 0x11, 0x4c, 0xc7, 0x1a, 0x8c, 0x87, 0xff,
	0x3f, 0xfd, 0xb8, 0x11, 0x8c, 0xe8, 0xbe, 0xe0, 0x14, 0xfa, 0x3f, 0x14, 0x02, 0xd8, 0xb3, 0x79,
	0x7c, 0x73, 0x37, 0xf1, 0x3a, 0xe8, 0x80, 0x35, 0x9d, 0xcf, 0x26, 0x9e, 0x51, 0xa3, 0xa7, 0x39,
	0xb9, 0xf5, 0xcc, 0xe0, 0x12, 0xdc, 0xab, 0xe6, 0x5e, 0x31, 0xe7, 0x2b, 0x0c, 0xc1, 0x16, 0x8c,
	0x8b, 0xbc, 0x3e, 0x4b, 0xbd, 0x88, 0xf7, 0xd7, 0x8d, 0xb4, 0x7a, 0xf0, 0x00, 0x3b, 0x0b, 0xc9,
	0x5f, 0xb3, 0x9c, 0xe1, 0x31, 0xf4, 0xb3, 0x82, 0xbe, 0xb1, 0x97, 0xb5, 0xcc, 0x9b, 0xec, 0xd3,
	0x0e, 0x71, 0x34, 0xb5, 0x94, 0x39, 0x9e, 0x00, 0x34, 0x72, 0x4a, 0x15, 0xd5, 0x5b, 0xec, 0x4e,
	0x3b, 0xa4, 0x19, 0xb9, 0xa6, 0x8a, 0xc6, 0x0e, 0xd8, 0xf4, 0x83, 0x2a, 0x2a, 0xe3, 0xbd, 0x67,
	0x57, 0x24, 0x67, 0x5b, 0xcb, 0xc4, 0xd6, 0xdf, 0x77, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x48,
	0x4f, 0x80, 0xd3, 0xd3, 0x01, 0x00, 0x00,
}
