// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol_type.proto

package demo_type

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	ValueDouble          float64  `protobuf:"fixed64,1,opt,name=value_double,json=valueDouble,proto3" json:"value_double,omitempty"`
	ValueFloat           float32  `protobuf:"fixed32,2,opt,name=value_float,json=valueFloat,proto3" json:"value_float,omitempty"`
	ValueInt32           int32    `protobuf:"varint,3,opt,name=value_int32,json=valueInt32,proto3" json:"value_int32,omitempty"`
	ValueInt64           int64    `protobuf:"varint,4,opt,name=value_int64,json=valueInt64,proto3" json:"value_int64,omitempty"`
	ValueUint32          uint32   `protobuf:"varint,5,opt,name=value_uint32,json=valueUint32,proto3" json:"value_uint32,omitempty"`
	ValueUint64          uint64   `protobuf:"varint,6,opt,name=value_uint64,json=valueUint64,proto3" json:"value_uint64,omitempty"`
	ValueSint32          int32    `protobuf:"zigzag32,7,opt,name=value_sint32,json=valueSint32,proto3" json:"value_sint32,omitempty"`
	ValueSint64          int64    `protobuf:"zigzag64,8,opt,name=value_sint64,json=valueSint64,proto3" json:"value_sint64,omitempty"`
	ValueFixed32         uint32   `protobuf:"fixed32,9,opt,name=value_fixed32,json=valueFixed32,proto3" json:"value_fixed32,omitempty"`
	ValueFixed64         uint64   `protobuf:"fixed64,10,opt,name=value_fixed64,json=valueFixed64,proto3" json:"value_fixed64,omitempty"`
	ValueSfixed32        int32    `protobuf:"fixed32,11,opt,name=value_sfixed32,json=valueSfixed32,proto3" json:"value_sfixed32,omitempty"`
	ValueSfixed64        int64    `protobuf:"fixed64,12,opt,name=value_sfixed64,json=valueSfixed64,proto3" json:"value_sfixed64,omitempty"`
	ValueBool            bool     `protobuf:"varint,13,opt,name=value_bool,json=valueBool,proto3" json:"value_bool,omitempty"`
	ValueString          string   `protobuf:"bytes,14,opt,name=value_string,json=valueString,proto3" json:"value_string,omitempty"`
	ValueBytes           []byte   `protobuf:"bytes,15,opt,name=value_bytes,json=valueBytes,proto3" json:"value_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_517ed17cbe96f4f2, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetValueDouble() float64 {
	if m != nil {
		return m.ValueDouble
	}
	return 0
}

func (m *Person) GetValueFloat() float32 {
	if m != nil {
		return m.ValueFloat
	}
	return 0
}

func (m *Person) GetValueInt32() int32 {
	if m != nil {
		return m.ValueInt32
	}
	return 0
}

func (m *Person) GetValueInt64() int64 {
	if m != nil {
		return m.ValueInt64
	}
	return 0
}

func (m *Person) GetValueUint32() uint32 {
	if m != nil {
		return m.ValueUint32
	}
	return 0
}

func (m *Person) GetValueUint64() uint64 {
	if m != nil {
		return m.ValueUint64
	}
	return 0
}

func (m *Person) GetValueSint32() int32 {
	if m != nil {
		return m.ValueSint32
	}
	return 0
}

func (m *Person) GetValueSint64() int64 {
	if m != nil {
		return m.ValueSint64
	}
	return 0
}

func (m *Person) GetValueFixed32() uint32 {
	if m != nil {
		return m.ValueFixed32
	}
	return 0
}

func (m *Person) GetValueFixed64() uint64 {
	if m != nil {
		return m.ValueFixed64
	}
	return 0
}

func (m *Person) GetValueSfixed32() int32 {
	if m != nil {
		return m.ValueSfixed32
	}
	return 0
}

func (m *Person) GetValueSfixed64() int64 {
	if m != nil {
		return m.ValueSfixed64
	}
	return 0
}

func (m *Person) GetValueBool() bool {
	if m != nil {
		return m.ValueBool
	}
	return false
}

func (m *Person) GetValueString() string {
	if m != nil {
		return m.ValueString
	}
	return ""
}

func (m *Person) GetValueBytes() []byte {
	if m != nil {
		return m.ValueBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "demo_type.Person")
}

func init() { proto.RegisterFile("protocol_type.proto", fileDescriptor_517ed17cbe96f4f2) }

var fileDescriptor_517ed17cbe96f4f2 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0x87, 0x33, 0xfc, 0x29, 0x74, 0x29, 0xf0, 0xbe, 0xeb, 0x65, 0x2f, 0xc6, 0x51, 0x63, 0x32,
	0x27, 0x4d, 0x60, 0xb3, 0x1f, 0x80, 0x18, 0x12, 0x6f, 0xa6, 0xc4, 0x8b, 0x97, 0x86, 0xca, 0x6a,
	0x48, 0x2a, 0x4b, 0xe8, 0x62, 0xe4, 0x83, 0xf8, 0x7d, 0x0d, 0xbb, 0x8b, 0x2d, 0x3d, 0xee, 0x93,
	0x67, 0x7e, 0x9d, 0xe9, 0x0c, 0xbb, 0xd8, 0xee, 0x8c, 0x35, 0x6f, 0xa6, 0xc8, 0xec, 0x61, 0xab,
	0xef, 0xdd, 0x8b, 0xc7, 0x2b, 0xfd, 0x69, 0x1c, 0xb8, 0xf9, 0xe9, 0xb0, 0xe8, 0x59, 0xef, 0x4a,
	0xb3, 0xe1, 0xd7, 0x2c, 0xf9, 0x5a, 0x16, 0x7b, 0x9d, 0xad, 0xcc, 0x3e, 0x2f, 0xb4, 0x00, 0x04,
	0x82, 0x74, 0xe0, 0xd8, 0xa3, 0x43, 0xfc, 0x8a, 0xf9, 0x67, 0xf6, 0x5e, 0x98, 0xa5, 0x15, 0x2d,
	0x04, 0x6a, 0xa5, 0xcc, 0xa1, 0xf9, 0x91, 0x54, 0xc2, 0x7a, 0x63, 0xa7, 0x13, 0xd1, 0x46, 0xa0,
	0x6e, 0x10, 0x9e, 0x8e, 0xe4, 0x4c, 0x50, 0x52, 0x74, 0x10, 0xa8, 0x5d, 0x09, 0x4a, 0x56, 0x5d,
	0xec, 0x7d, 0x44, 0x17, 0x81, 0x86, 0xa1, 0x8b, 0x17, 0x87, 0xce, 0x15, 0x25, 0x45, 0x84, 0x40,
	0x9d, 0x9a, 0x52, 0x4f, 0x29, 0x7d, 0x4a, 0x0f, 0x81, 0xfe, 0x07, 0x65, 0xd1, 0x48, 0x29, 0x7d,
	0x4a, 0x1f, 0x81, 0x78, 0x4d, 0x51, 0x92, 0xdf, 0xb2, 0x61, 0x18, 0x77, 0xfd, 0xad, 0x57, 0xd3,
	0x89, 0x88, 0x11, 0xa8, 0x97, 0xfa, 0xba, 0xb9, 0x67, 0x0d, 0x49, 0x49, 0xc1, 0x10, 0x28, 0xaa,
	0x4b, 0x4a, 0xf2, 0x3b, 0x36, 0x0a, 0x1f, 0x3b, 0x45, 0x0d, 0x10, 0x68, 0x9c, 0xfa, 0xd2, 0x45,
	0x80, 0x4d, 0x4d, 0x49, 0x91, 0x20, 0xd0, 0xbf, 0x33, 0x4d, 0x49, 0x7e, 0xc9, 0xfc, 0x1f, 0xcb,
	0x72, 0x63, 0x0a, 0x31, 0x44, 0xa0, 0x7e, 0x1a, 0x3b, 0x32, 0x33, 0xa6, 0xa8, 0x4d, 0x66, 0x77,
	0xeb, 0xcd, 0x87, 0x18, 0x21, 0x50, 0x7c, 0x9a, 0xcc, 0xa1, 0x6a, 0x0d, 0xf9, 0xc1, 0xea, 0x52,
	0x8c, 0x11, 0x28, 0x09, 0x6b, 0x98, 0x1d, 0xc9, 0x6c, 0xf4, 0x9a, 0x6c, 0xf3, 0x87, 0xbf, 0x3b,
	0xc9, 0x23, 0x77, 0x39, 0xd3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x1c, 0x37, 0xc1, 0x50,
	0x02, 0x00, 0x00,
}
